/**
 * Evidence Dossier Builder
 * Formats the structured Evidence Dossier and builds the LLM Context Prompt Block
 * enforcing strict citation integrity, contradiction transparency, and confidence bounds.
 */

import type { EvidenceDossier, InspectedSource, VerifiedClaim, ContradictionRecord } from "./types";
import { getRuntimeTemporalContext } from "./temporal-engine";

export function buildEvidenceDossier(
  query: string,
  inspectedSources: InspectedSource[],
  verifiedClaims: VerifiedClaim[],
  contradictions: ContradictionRecord[],
  unresolvedQuestions: string[] = [],
  summaryOfEvidence: string = ""
): EvidenceDossier {
  const temporalCtx = getRuntimeTemporalContext();

  // Compute overall confidence score
  let overallConfidence: "HIGH" | "MEDIUM" | "LOW" | "UNVERIFIED" = "MEDIUM";
  const verifiedCount = verifiedClaims.filter((c) => c.status === "VERIFIED").length;
  const accessibleCount = inspectedSources.filter((s) => s.accessible).length;
  const hasPrimary = inspectedSources.some((s) => s.isPrimary);

  if (accessibleCount === 0 || verifiedClaims.every((c) => c.status === "UNVERIFIED" || c.status === "UNSUPPORTED")) {
    overallConfidence = "UNVERIFIED";
  } else if (hasPrimary && verifiedCount >= 2 && contradictions.length === 0) {
    overallConfidence = "HIGH";
  } else if (verifiedCount >= 1 && contradictions.length === 0) {
    overallConfidence = "MEDIUM";
  } else {
    overallConfidence = "LOW";
  }

  return {
    query,
    runtimeDate: temporalCtx.runtimeIso,
    runtimeDateFormatted: temporalCtx.runtimeFormatted,
    inspectedSources,
    verifiedClaims,
    contradictions,
    unresolvedQuestions,
    overallConfidence,
    summaryOfEvidence,
  };
}

/**
 * Format the Evidence Dossier into an authoritative prompt block for the Main AI.
 */
export function formatDossierForMainAI(dossier: EvidenceDossier): string {
  const accessibleSources = dossier.inspectedSources.filter((s) => s.accessible);

  let output = `\n\n═══════════════════════════════════════════════════════════════════\n`;
  output += `📋 VERIFIED EVIDENCE DOSSIER (Generated by Studio AI Research Agent)\n`;
  output += `Runtime Anchor Date: ${dossier.runtimeDateFormatted} (ISO: ${dossier.runtimeDate})\n`;
  output += `Overall Research Confidence: ${dossier.overallConfidence}\n`;
  output += `═══════════════════════════════════════════════════════════════════\n\n`;

  // 1. Inspected Sources Table
  output += `### 1. INSPECTED & VERIFIED SOURCES (${accessibleSources.length})\n`;
  if (accessibleSources.length === 0) {
    output += `No external web sources could be inspected.\n\n`;
  } else {
    accessibleSources.forEach((s, idx) => {
      output += `[Source ${idx + 1}] ${s.title}\n`;
      output += `  • URL: ${s.url}\n`;
      output += `  • Domain Authority: ${s.quality} (Primary: ${s.isPrimary ? "YES" : "NO"})\n`;
      output += `  • Published/Updated Date: ${s.publishedDate || "Unknown"}\n`;
      if (s.isWireOrSyndicated) {
        output += `  • Wire Syndication: Originated from ${s.wireAgency || "Wire Service"} (Not an independent confirmation)\n`;
      }
      output += `  • Excerpt: "${s.text.slice(0, 300)}..."\n\n`;
    });
  }

  // 2. Claim-Level Verification Matrix
  output += `### 2. CLAIM-LEVEL VERIFICATION MATRIX\n`;
  if (dossier.verifiedClaims.length === 0) {
    output += `No empirical claims could be verified from available text.\n\n`;
  } else {
    dossier.verifiedClaims.forEach((c, idx) => {
      output += `Claim ${idx + 1}: "${c.claim}"\n`;
      output += `  • Verification Status: [${c.status}] (Confidence: ${Math.round(c.confidenceScore * 100)}%)\n`;
      output += `  • Temporal Chronology: ${c.temporalStatus} (Source Date: ${c.sourcePublicationDate || "N/A"})\n`;
      output += `  • Verbatim Quote Match: ${c.exactQuoteMatch ? "YES" : "APPROXIMATE / SEMANTIC"}\n`;
      output += `  • Supporting URL: ${c.primarySourceUrl || "N/A"}\n`;
      output += `  • Evidence Note: ${c.reasoning}\n\n`;
    });
  }

  // 3. Contradictions & Disputed Facts (if any)
  if (dossier.contradictions.length > 0) {
    output += `### 3. ⚠️ CONFLICTS & CONTRADICTIONS DETECTED\n`;
    dossier.contradictions.forEach((ct, idx) => {
      output += `Conflict ${idx + 1}: ${ct.topic}\n`;
      output += `  • Position A: "${ct.claimA.statement}" (Source: ${ct.claimA.sourceUrl} | Date: ${ct.claimA.sourceDate || "Unknown"})\n`;
      output += `  • Position B: "${ct.claimB.statement}" (Source: ${ct.claimB.sourceUrl} | Date: ${ct.claimB.sourceDate || "Unknown"})\n`;
      output += `  • Resolution Guidance: ${ct.resolution} — ${ct.reasoning}\n\n`;
    });
  }

  // 4. Mandatory Citation & Grounding Directives
  output += `### 4. INSTRUCTIONS FOR FINAL ANSWER GENERATION:\n`;
  output += `1. Answer strictly based on the verified evidence dossier above.\n`;
  output += `2. CITE ONLY the inspected URLs listed above. NEVER fabricate, hallucinate, or guess URLs, dates, or statistics.\n`;
  output += `3. If there are contradictions or outdated predictions, transparently explain both sides with their respective dates.\n`;
  output += `4. If confidence is LOW or UNVERIFIED, clearly state that evidence is limited or unconfirmed.\n`;
  output += `5. Current Year is ${new Date(dossier.runtimeDate).getFullYear()}. Always use past tense for completed past events and future tense ONLY for confirmed upcoming events.\n\n`;

  return output;
}
